### ISSUE TITLE
😒

### ISSUE THREAD

**Issue by senolfndk** [sosauce/CuteMusic#13]
the app is not responding
![Screenshot_20240504-193221_CuteMusic.jpg](https://github.com/sosauce/CuteMusic/assets/52818836/7e8c7cf3-f8a8-4108-b121-9e1a1c1b8df8)

**Comment by senolfndk** [comment]
![Screenshot_20240504-193221_CuteMusic.jpg](https://github.com/sosauce/CuteMusic/assets/52818836/7e617507-d86c-45ea-976a-4d1d8e0528b7)

**Comment by sosauce** [comment]
Yeah I think it happens when you have alot of songs, press wait and should finish by working. I'm working on it sorry 😓

**Comment by sosauce** [comment]
Hi again ! Could install this apk and tell me if its fixed/ faster ? (Google Drive because GitHub doesnt support APKs)

https://drive.google.com/file/d/1aIUPfVGWc8OLr5A55nHmlMYDeGDSQ3Mb/view?usp=sharing

**Comment by senolfndk** [comment]
same problem

**Comment by sosauce** [comment]
Hello again ! Could you test this version : https://gofile.io/d/ALGujg

If it doesnt change anything, could you try providing logs please?

**Comment by senolfndk** [comment]
> Hello again ! Could you test this version : https://gofile.io/d/ALGujg
> 
> If it doesnt change anything, could you try providing logs please?

This is not working bro ☹️

**Comment by sosauce** [comment]
Do you have logs ? 😔

**Comment by senolfndk** [comment]
> Do you have logs ? 😔

No, I'm not an expert on this, how to get it?

**Comment by sosauce** [comment]
https://developer.android.com/tools/logcat

**Comment by senolfndk** [comment]
> https://developer.android.com/tools/logcat

Can you show it visually?

**Comment by senolfndk** [comment]
> https://developer.android.com/tools/logcat

Can you show it visually?

**Comment by sosauce** [comment]
Launch the app, then in your terminal, use the command 

adb logcat -b main | grep com.sosauce.cutemusic

If you don't have adb on your PC, you can install it using this tutorial : https://www.xda-developers.com/install-adb-windows-macos-linux/

**Comment by senolfndk** [comment]
Where am I doing wrong?

https://github.com/sosauce/CuteMusic/assets/52818836/730849eb-e7f2-4b38-a1aa-491ef2e44988

**Comment by sosauce** [comment]
It's because you are using PowerShell here, you need to use CMD

**Comment by sosauce** [comment]
Hi! It's been a while, but can you test this : https://drive.google.com/file/d/1Y4HOrKWAyZnUjFPWWbSp1uVuo3ybPIZ_/view?usp=sharing

Should have optimized and change some things, wanna know how it goes for you !
