### ISSUE TITLE
Adding compose previews 

### ISSUE THREAD

**Issue by tuuhin** [sosauce/CuteMusic#17]
This isn't a feature request to be honest .
Compose previews reduces development time and provide direct interactive previews for the composable functions.

**Comment by sosauce** [comment]
Yo hi, I've already tried that but I have a pretty old MacBook, testing on my actual phone is much faster and easier for me 🤷‍♂️

**Comment by sosauce** [comment]
But if you fork the project or wanna use previews feel free to

**Comment by sosauce** [comment]
Okay I'll do it, not that I don't want your PR, but at this point in time, I've restructed all packages and rewritten lots of stuff, your PR might be broken. Open it and I'll see if I can merge it

**Comment by tuuhin** [comment]
Let me complete my work, I will post the PR soon.
