### ISSUE TITLE
Not finding all audio files on my device

### ISSUE THREAD

**Issue by realeatham** [sosauce/CuteMusic#2]
OS: android 14 one UI 
App version: Beta 1 (Build 1)
Screenshots of both cute music and Fossify music

![Screenshot_20240414_201308_CuteMusic](https://github.com/sosauce/CuteMusic/assets/136866675/91cf9201-5c9e-4eb7-b47f-1a33e74a3200)

![Screenshot_20240414_201312_Music Player](https://github.com/sosauce/CuteMusic/assets/136866675/19148d09-f2f4-469a-ade5-f6b226ffcd72)

**Comment by sosauce** [comment]
Oh I think that's because MediaStore skips folder like ringtones etc...
Should add then yeah

**Comment by realeatham** [comment]
Yeah, it should ideally show all the audio

**Comment by realeatham** [comment]
Should be closed as non completed.

**Comment by sosauce** [comment]
Why ? It is completed in v1.1.0 no ?

**Comment by realeatham** [comment]
There's a new Version? Sorry I didn't realize

**Comment by realeatham** [comment]
I will check if fixed

**Comment by sosauce** [comment]
It's okay ^^ I hope its fixed, for me it found music in root folders

**Comment by realeatham** [comment]
Still didn't find it, no clue what's wrong. It doesn't find stuff recorded locally

**Comment by sosauce** [comment]
Oh maybe recording from recording apps aren't  taken into consideration with the MediaStore, imma check how fossify handles it

**Comment by realeatham** [comment]
Maybe tgd player doesn't support m4a files?

**Comment by sosauce** [comment]
It does I just checked, when placing the recording in lets say Music file it finds it, but when placing it Recordings folder it doesn't, meaning MediaStore skips these folders

**Comment by realeatham** [comment]
Can't you tell it to search all?

**Comment by sosauce** [comment]
sure ^^

**Comment by realeatham** [comment]
You should open this issue until it is solved

**Comment by sosauce** [comment]
Nah imma leave it closed since most people only care about actual music, if someone opens a new issue thats okay ^^
