### ISSUE TITLE
Request for Skip Forward/Backward Feature in CuteMusic App

### ISSUE THREAD

**Issue by akashsriramganapathy** [sosauce/CuteMusic#22]
**Is your feature request related to a problem? Please describe.**
The CuteMusic app currently lacks a feature for seeking forward or backward in a track. This omission affects my music listening experience, as I have to drag the progress bar to navigate through songs manually.

**Describe the solution you'd like**
I want the CuteMusic app to implement dedicated buttons for skipping forward and backward by 10 seconds. This feature would greatly improve the music listening experience by allowing precise and easy navigation through tracks.

**Describe alternatives you've considered**
An enhancement to this feature could be implementing double-tap gestures. For example, double-tapping on the right side of the screen to seek forward and on the left side to seek backward.

**Comment by sosauce** [comment]
Noted 😁
