### ISSUE TITLE
Reproducible Builds fail

### ISSUE THREAD

**Issue by IzzySoft** [sosauce/CuteMusic#23]
At IzzyOnDroid, we've established Reproducible Builds for your app (see: [Reproducible bulds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients). While for v1.3.0, we only had to perform a soft-reset to the embedded commit hash, since v1.4.0 that fails, too, as there are also [differences in `resources.arsc`](https://gist.github.com/obfusk/f0460dcdb21396ba3d2cc9db56bb40ae#differing-resourcesarsc-address-first):

```diff
   resources.arsc
-  32-bit CRC value (hex):                         de90c2f7
+  32-bit CRC value (hex):                         9c1b372a
```

Which often is a sorting issue, but here it seems you've added some language strings after the commit, and then built without committing/pushing:

```diff
--- /dev/fd/63  2024-08-13 20:31:02.341146709 +0200
+++ /dev/fd/62  2024-08-13 20:31:02.341146709 +0200
@@ -3293,53 +3293,79 @@
       (zh-rTW) "Menu +"
     resource 0x7f0e001c string/albums
       () "Albums"
+      (ro) "Albume"
       (fr) "Albums"
+      (tr) "Albümler"
       (es) "Álbumes"
     resource 0x7f0e001d string/alrdy_blacklisted
       () "Folder already blacklisted!"
+      (ro) "Folder deja este exclusată !"
       (fr) "Dossier déjà blacklisté!"
+      (tr) "Klasör zaten kara listede!"
     resource 0x7f0e001e string/amoled_mode
       () "Amoled Mode"
+      (ro) "În mod Amoled"
       (fr) "Mode Amoled"
+      (tr) "Amoled Mod"
```

Are your APKs really built from a clean tree at the commit the tag points to? Looks like not.

We'd appreciate if you could help making your build reproducible again. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

**Comment by sosauce** [comment]
Oopsies, forgot to push my code let me push it... 😥

**Comment by sosauce** [comment]
Oopsies, releasing 1.4.2 in like 10 minutes!

**Comment by sosauce** [comment]
1.4.2 released, should be all good now

**Comment by IzzySoft** [comment]
Sorry, but not RB:

```diff
-------------------------------
--- /dev/fd/63  2024-08-13 23:06:32.739511210 +0200
+++ /dev/fd/62  2024-08-13 23:06:32.743511182 +0200
@@ -3,11 +3,11 @@
   META-INF/version-control-info.textproto
   32-bit CRC value (hex):                         65b44d2c
   assets/dexopt/baseline.prof
-  32-bit CRC value (hex):                         8ad9058e
+  32-bit CRC value (hex):                         70a12081
   assets/dexopt/baseline.profm
   32-bit CRC value (hex):                         c541803c
   classes.dex
-  32-bit CRC value (hex):                         c0824fcc
+  32-bit CRC value (hex):                         b4827c40
   lib/arm64-v8a/libandroidx.graphics.path.so
   32-bit CRC value (hex):                         9734baa0
   lib/arm64-v8a/libdatastore_shared_counter.so
```


You sure build that APK from a clean tree at the tag? What are you using to build it? If Android Studio, did you make sure to run "clean" first? Giving you a small part of the Dex diff in the hope it gives you a clue:

```diff
 |: const/16 v21, #int 0 // #0
-|: const/16 v23, #int 48 // #30
+|: const v23, #float 2.20412e-39 // #00180030
 |: const-wide/16 v3, #int 0 // #0
 |: const-wide/16 v5, #int 0 // #0
 |: const/4 v7, #int 0 // #0
@@ -294647,7 +294647,7 @@
 |: invoke-static/range {v13, v14, v15, v16, v17, v18}, Landroidx/compose/foundation/layout/a;.l:(Le0/q;FFFFI)Le0/q;
 |: move-result-object v2
 |: const/16 v21, #int 0 // #0
-|: const/16 v23, #int 48 // #30
+|: const v23, #float 2.20412e-39 // #00180030
 |: const-wide/16 v3, #int 0 // #0
 |: const-wide/16 v5, #int 0 // #0
 |: const/4 v7, #int 0 // #0
@@ -294690,7 +294690,7 @@
 |: invoke-static/range {v13, v14, v15, v16, v17, v18}, Landroidx/compose/foundation/layout/a;.l:(Le0/q;FFFFI)Le0/q;
 |: move-result-object v2
 |: const/16 v21, #int 0 // #0
-|: const/16 v23, #int 48 // #30
+|: const v23, #float 2.20412e-39 // #00180030
 |: const-wide/16 v3, #int 0 // #0
```

Looks like some `int` have been changed to `float` – but analyzing a Dex diff is beyond my expertise…

**Comment by sosauce** [comment]
I indeed use Android Studio, I didn't use Clean but never did and it used to work, next release I will use Clean

**Comment by sosauce** [comment]
Analyzing Dex is also too much for me..

**Comment by sosauce** [comment]
@IzzySoft I have changed the APK in the release, it was cleaned before building (using AS)

**Comment by IzzySoft** [comment]
> I didn't use Clean but never did and it used to work

Sure it "works" – as long as you don't care about reproducibility. Without clean, parts from previous builds are reused at your end – but not at the verification builder. Which then leads to differences.

> I have changed the APK in the release

Oof… that APK was already distributed, and hence won't be "pulled" again by those already having the APK that was at that release before (end-devices as well as IoD as well as Obtainium etc). So it's not a good idea to replace what was already distributed, better make another "maintenance release" when a replacement is needed. Too late now, though – so let me test-run the new APK…

Yupp, that was it! That APK is reproducible. Glad we found the culprit – and thanks for having taken care! So for future releases, can you please always run "clean" before building the APK for release? For "non-release APKs" (e.g. test builds between releases) it's not important, but for the release build it would be. Thanks in advance!

PS: As that's the APK at the release (which you hopefully do not replace again), I'll now commit those changes. The release won't show as RB at the IoD repo, though, as that has the previous APK. Instead it will show as "untested" for v1.4.2. Future release then hopefully will have the green shield again.
