### ISSUE TITLE
UTF-8 Characters Break CuteMusic

### ISSUE THREAD

**Issue by quantenzitrone** [sosauce/CuteMusic#25]
**Describe the bug**
I have mp3 songs by 𝔐oon 𝔇eity. The 𝔐 and 𝔇 is shown as `????` in the app. Trying to play them freezes CuteMusic.

```
$ python3
>>> import mutagen
>>> f = mutagen.File('myfile.mp3')
>>> f.get('TPE1')
TPE1(encoding=<Encoding.UTF8: 3>, text=['𝔐oon 𝔇eity'])
```

**To Reproduce**
Obtain an mp3 with non-ASCII UTF-8 encoded metadata and try to use it in CuteMusic.

**Expected behavior**
Proper Unicode handling.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: SHIFT6m
 - OS: Android 8.1
 - Version: 1.4.2

**Additional context**

**Comment by sosauce** [comment]
Hello, I've tried running the python code but I've been getting the below error, I have no knowledge in Python

![image](https://github.com/user-attachments/assets/f42e3088-f479-4ba8-9d3e-d727e640ffce)
![image](https://github.com/user-attachments/assets/b2af4def-ecf4-4577-9d12-9c9bdf605044)

**Comment by quantenzitrone** [comment]
line 6 is not code
it is the output of line 4
My code was meant to illustrate and prove the UTF-8-ness of my ID3 tags.

**Comment by quantenzitrone** [comment]
im not sure if you get any output if you run it as a script, i ran it in a python repl

**Comment by sosauce** [comment]
Oh, well when I modified the title of a mp3 file using another app (using the exact characters you gave me) the app worked fine 🤔

**Comment by quantenzitrone** [comment]
try https://quantenzitrone.eu/filehost/wake%20up!.mp3

i can't upload mp3s to github so i put it on my vps

**Comment by sosauce** [comment]
Mhmm, works fine on both of my phone (One is running CrDroid Android 14, the other one is MIUI 14 Android 13) I think the issues is coming from your OS

**Comment by quantenzitrone** [comment]
When I go into the system settings and `Storage` > `Music & audio` > `Audio files`, my phone opens the AOSP file manager, which also shows `𝔐oon 𝔇eity` as `????oon ????eity`. I'm guessing this uses the same API as Cutemusic and my phone has a bug in that API. 
The app responsible for provding this music file index is `com.android.providers.media`. 
While fiddling, I actually managed for cutemusic to freeze on any file, and after clearing this app's data (which you probably shouldn't do) the freezing problem went away. 
But  `𝔐oon 𝔇eity` hasn't been indexed again yet, so I don't really know.
I'll try fiddling around a bit more. I still think the freezing might be a bug. Maybe some unhandled exception.

**Comment by sosauce** [comment]
Probably yes, I'll add a workaround. Do you have any logs of when the app freezes ? This would let me know what error to catch

**Comment by quantenzitrone** [comment]
how do i get logs of freezes?
I have [scoop](https://f-droid.org/en/packages/taco.scoop/) that catches logs of crashes, but freezes?

**Comment by sosauce** [comment]
It should do it, I just want to see what happens during runtime so scoop should do it

**Comment by sosauce** [comment]
Re-open this if you have stack traces
