### ISSUE TITLE
Find music from SD card

### ISSUE THREAD

**Issue by pythonian23** [sosauce/CuteMusic#26]
**Is your feature request related to a problem? Please describe.**
All of my music is stored in my SD card, and it seems Cute Music doesn't search the SD card for music

**Describe the solution you'd like**
The app should also search in the SD card

**Describe alternatives you've considered**
A way to select where to source music files from (like the blacklist but reversed) would also be useful in solving this issue

**Additional context**
Love the app though; keep up the good work!

**Comment by sosauce** [comment]
Hello, thanks for the issue and support ! As I do not have an SD Card, I will try my best hoping it does work in the next update  🙏  Unless there is a way to simulate an SD Card which if you know of let me know !

**Comment by sosauce** [comment]
Oh and also do you know how many musics you have approx ?

**Comment by pythonian23** [comment]
> Oh and also do you know how many musics you have approx ?
Around 250 .flac files and 206 .mp3 files

**Comment by sosauce** [comment]
mhmm I've heard some issue with tons of musics (but it was like 1k sooo)but I think 200 mp3 is fine. Flac files tho, I need to make sure MediaStore actually scans for these, as they seem obscure, will check

**Comment by pythonian23** [comment]
I haven't updated or touched the app but it started detecting all the music on my SD card today

**Comment by sosauce** [comment]
Ooo well thats random but cool ^^
