### ISSUE TITLE
Feature request: Pitch and Volume

### ISSUE THREAD

**Issue by arythmitical** [sosauce/CuteMusic#27]
It would be awesone to play around with music by giving an option to separate speed from pitch.

**Describe the solution you'd like**
A pitch button next to the speed button in the music player screen. You can also make an option to synchrozine both sliders.

**Comment by sosauce** [comment]
Good request :) I overlooked this for 2.0.0 (I dont know why it was marked as read) so I'll add it in next update!

**Comment by sosauce** [comment]
Avaible on v2.1.0 !
