### ISSUE TITLE
Player shows duplicate albums due to my file structure.

### ISSUE THREAD

**Issue by realeatham** [sosauce/CuteMusic#34]
**Describe the bug**
CuteMusic expects each album to have it's own folder. Due to limitations to how lyrics work on my music player, I do this file structure : artist > album > song > song file.

As all the files have the album metadata, it would be good if albums could be figured out by the metadata first and file structure as a backup. 

**Screenshots**
![Screenshot_20241006_230027_CuteMusic](https://github.com/user-attachments/assets/ef1d7ad2-286f-4910-8306-9dd5371dfa31)

**Smartphone:**
 - Device: S21
 - OS Version: Android 14 OneUI 6.1
 - App Version: 2.2.0

**Additional context**
Weirdly, billy Joel albums load fine. It is only the green day and a few other artist's songs that have this problem.

Opening a duplicate album shows all the songs in all the folders for that album.

**Comment by realeatham** [comment]
Fossify music also does this, auxio doesn't do this but has a similar issue.

**Comment by sosauce** [comment]
Its due to how to quering albums works, that's more of an Android problem, but I can probably work a workaround

**Comment by sosauce** [comment]
Now it should be all good ^^

**Comment by realeatham** [comment]
Thank you! It works very well now
