### ISSUE TITLE
(MIUI 12) Timeline on miniplayer not showing up on a specific condition

### ISSUE THREAD

**Issue by thobaut** [sosauce/CuteMusic#40]
In the miniplayer, timeline doesn't show up sometimes
As far as I observed, it only happens when the song doesn't have any album image

- **Screenshots**
With album image :
![CuteMusicWithAlbumImage](https://github.com/user-attachments/assets/f2bf0674-102d-4dc2-8f2a-dcdb8135dfe1)
Without album image :
![CuteMusicWithoutAlbumImage](https://github.com/user-attachments/assets/138b6a40-6c93-4d7a-9cc7-fbbc48d74dad)

 - Device: Xiaomi Mi 9T
 - OS: Android 11
 - Version: MIUI 12.1.1

**Comment by sosauce** [comment]
I test the app on an AOSP ROM, as far as I can tell the timeline bug is MIUI specific, and for the icon, I didnt know it has an icon in the status bar ! 🤔

**Comment by sosauce** [comment]
Have you tried other music apps to see if they have the same issue with the timline ?

**Comment by thobaut** [comment]
Hi, thank you for the fast answer
Bad news, I tried Symphony and my stock MiMusic and it doesn't happen on both
For the status bar icon, it simply looks like a circke with a triangle in it

+ I really like your little minimalistic music player, I really want to stick with it
If I had skills in Kotlin (+ Android Studio I guess) i would definitely try to contribute more

**Comment by sosauce** [comment]
Ahah thanks 😁 Next update is a bugfix update so I'll include this on the list!
