### ISSUE TITLE
Audio not playing after relaunch

### ISSUE THREAD

**Issue by AnonymousX1025** [sosauce/CuteMusic#42]
The audio is not playing when I reopen the app after closing it.

 - Device: Realme 11 Pro
 - OS: Color OS
 - Version: 14

https://github.com/user-attachments/assets/ed2af3de-ad34-4e83-96f1-5cbd31cc4c48

**Comment by sosauce** [comment]
Hello ! I'm aware of this issue, I've got it to, it's being fixed!
