### ISSUE TITLE
List of bugs I've found

### ISSUE THREAD

**Issue by thobaut** [sosauce/CuteMusic#43]
Hey it's me again
I wanted to share a list of bugs I have encountered. They are more annoyances than anything else, so nothing should be too critical
Since the next update should be a bugfix update, it might help

**Device** : Xiaomi Mi9T
**Version** : MIUI 12
**OS** : Android 11

- **Editing music info not working**
-> Nothing too complicated here, it just doesn't work at all for me

- **Crash on trying to edit music infos**
-> It happened to me few times in a row, but couln't replicate it consistently. My best guess would be because a music is playing but sometimes it crashes, sometimes not
Same for the lyrics tab in the player. Sometimes it crashes by tapping on it, sometimes not

- **Playlist ends for no reason**
-> I have 40-50 songs in my library and I play random shuffle everytime
But for some reason at a somewhat random point, the app considers there are no more songs to play and simply stops at the end of the song
I can't say an exact number but it's clearly not 40-50, might be around 10-15-20 songs

**Comment by thobaut** [comment]
Nevermind for bug n°1
Issue has been covered right before mine on #42

**Comment by sosauce** [comment]
Bug 1 should be fixed now in 2.2.3

Does bug 5 happen only with shuffle mode ? Could potentially be a Media3 bug but I can't tell yet

**Comment by thobaut** [comment]
After my tests, it seems like it's a yes
For normal mode, I got to the end every single time
For shuffle mode, it was very random. Sometimes it went through almost the full library and sometimes it just stops after... 3 songs

So yes, shuffle mode seems to be the problem

**Comment by sosauce** [comment]
Okay thanks ! I'll do some research, and open an issue on the Media3 repo if it's from that !

**Comment by sosauce** [comment]
Update : https://github.com/androidx/media/issues/272

Had been reported already

**Comment by sosauce** [comment]
I've closed your issues since I grouped them in one #47 to make it easier for me to track down what's to do 😁
