### ISSUE TITLE
Another list of enhancement ideas

### ISSUE THREAD

**Issue by thobaut** [sosauce/CuteMusic#44]
Hey, it's me again
I came back for more ideas to further improve the app
It covers some QoL improvement, UI's shenanigans and a special request that I'm 99.99999% sure it's a dumb idea

- **Illogical time layout on player**
-> Total duration of the music is on the left and the current elapsed time on the right... Why ? It's really weird and unintuitive, it should be the opposite
Maybe it's a delibarate choice of yours and in that case that's completely fine
But I personally find it pretty disturbing

- **Typing speed or pitch value**
-> Instead of a always a slider, why not adding a custom value by typing it
Can be good for people with fat fingers
I was imagining that the value displayed is tappable and opens the keyboard for us to input a custom value

- **Difficult to select the very last song**
-> Let's say I want to specifically listen to the very last song of the library. Tapping on it is pretty difficult since the search menu at the bottom partially covers it

- **No option to quit the song**
-> Some music players offers the possibility to totally "close" a song, hence closing the mini player that accompanies it
Not the most useful feature, but I think it adds a little thing

- **Random button : The return**
-> First, I want to thank you for adding the random button on startup
But my problem is that... It disappears forever after pressing it
Let's say I'm not in the mood for **this** song it randomly gave me, I'd like to have a quick option to select another random one

- **Special request : Port to iOS**
-> I've heard about a tool from Google for Android developers that translates Java source code into Objective-C for the iOS (J2ObjC)
Since the app is in Kotlin, I can totally understand that this idea might be a dumb one or you're just too lazy to do it (pretty much requires a Mac apparently), so I'm not hoping seeing it the light of day, but I still put it there because we never know
More information here if you're interested : https://developers.google.com/j2objc/
(For context, I was offered an iPhone 12 recently because my Android is 5 years old, it is currently dying. Since I want to stick with your little music player, an iOS port would be amazing)

**Comment by sosauce** [comment]
Hello! So for the ios port, as someone who doesn't like Iphones, I don't have one to test on, plus it does require a mac as you said, I have a 2013 macbook but it only run Big Sure, which xcode doesnt support. Plus I'd have to learn Ios specific API's 😕

**Comment by sosauce** [comment]
For your other request, I can do them no problem ^^

**Comment by sosauce** [comment]
Oh and for closing the song, do you have any apps that do that ?

**Comment by thobaut** [comment]
I knew it was a pretty bad idea and yeah, I hate Apple too. But I think their products are good, just really overpriced
It was just a little idea I had, I wasn't expecting it to be added

For closing songs, I know that Symphony closes the song by swiping down the miniplayer at the bottom
MiMusic does that too I think (not sure since I recently uninstalled the updates to take less space on my phone)
I find that pretty impractical, a simple X button would be clearer and easier

**Comment by sosauce** [comment]
Closing since I won't be porting to ios !
