### ISSUE TITLE
Searching for folders

### ISSUE THREAD

**Issue by maliprinc420** [sosauce/CuteMusic#48]
Hello,

I mainly organize my music inside folders and most of the songs don't have any artists nor albums set. So is it planned to add a way to search for folders the same way it is for searching for titles/artists/albums?

**Comment by sosauce** [comment]
I can add a way to filter by folders yes ! But if it's about a folders tab, I'm not sure about this one yet

**Comment by sosauce** [comment]
Mhmm, I'll look into it !

**Comment by sosauce** [comment]
Sorry for the oopsie 😅
