### ISSUE TITLE
Top search results not visible when the keyboard is active

### ISSUE THREAD

**Issue by maliprinc420** [sosauce/CuteMusic#51]
**Describe the bug**
The top search results are not visible on the screen when the keyboard is active (i.e. when typing in the search bar). But when the keyboard is hidden, those results are visible.

**Smartphone (please complete the following information):**
 - OS: Android
 - Version: 14

**Comment by sosauce** [comment]
Hello ! That's because the keyboard pushes the results out of view, and I # agree it's not very optimal, will find a solution
