### ISSUE TITLE
Build of v2.3.2 fails with lint errors

### ISSUE THREAD

**Issue by IzzySoft** [sosauce/CuteMusic#54]
Unfortunately, the (reproducible) build of v2.3.2 failed, so this release will **not** have its green shield up. So just letting you know so you can fix it:

```
> Task :app:lintVitalRelease FAILED
/build/repo/app/src/main/res/values-ro/strings.xml:33: Error: "restart_app" is translated here but not found in default locale [ExtraTranslation]
    <string name="restart_app">Reporne?te applica?ia</string>
            ~~~~~~~~~~~~~~~~~~
/build/repo/app/src/main/res/values-tr/strings.xml:33: Error: "restart_app" is translated here but not found in default locale [ExtraTranslation]
    <string name="restart_app">Uygulamay? Yeniden Ba?lat?n</string>
            ~~~~~~~~~~~~~~~~~~
/build/repo/app/src/main/res/values-es/strings.xml:34: Error: "restart_app" is translated here but not found in default locale [ExtraTranslation]
    <string name="restart_app">"Reiniciar la app"</string>
            ~~~~~~~~~~~~~~~~~~
/build/repo/app/src/main/res/values-fr/strings.xml:34: Error: "restart_app" is translated here but not found in default locale [ExtraTranslation]
    <string name="restart_app">Red?marrer l\'app</string>
            ~~~~~~~~~~~~~~~~~~
/build/repo/app/src/main/res/values-ro/strings.xml:34: Error: "restart_app_why" is translated here but not found in default locale [ExtraTranslation]
    <string name="restart_app_why">Dac? se ?nt?mpl? probleme.</string>
            ~~~~~~~~~~~~~~~~~~~~~~
/build/repo/app/src/main/res/values-tr/strings.xml:34: Error: "restart_app_why" is translated here but not found in default locale [ExtraTranslation]
    <string name="restart_app_why">Sorun ya??yorsan?z.</string>
            ~~~~~~~~~~~~~~~~~~~~~~
/build/repo/app/src/main/res/values-es/strings.xml:35: Error: "restart_app_why" is translated here but not found in default locale [ExtraTranslation]
    <string name="restart_app_why">"Si enfrentas problemas"</string>
            ~~~~~~~~~~~~~~~~~~~~~~
/build/repo/app/src/main/res/values-fr/strings.xml:35: Error: "restart_app_why" is translated here but not found in default locale [ExtraTranslation]
    <string name="restart_app_why">Si vous encontrez des probl?mes</string>
            ~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "ExtraTranslation":
   If a string appears in a specific language translation file, but there is
   no corresponding string in the default locale, then this string is probably
   unused. (It's technically possible that your application is only intended
   to run in a specific locale, but it's still a good idea to provide a
   fallback.)

   Note that these strings can lead to crashes if the string is looked up on
   any locale not providing a translation, so it's important to clean them
   up.

8 errors, 0 warnings


FAILURE: Build failed with an exception.
```

**Comment by sosauce** [comment]
Oh shoot, I'll only be able to fix tomorrow night (GMT +1)

**Comment by IzzySoft** [comment]
For now I've kept the logs back, in the hope it can be fixed somehow on our end. You were able to build, so there might be a way, and unless it involves something cached on your end…

Quick thought: If you really built from the very commit the tag points to, with no "dirty tree", maybe we could pass some `-x` to the gradlew call to skip the lint check. After all, the APK we build won't be distributed anyway, it's just for comparing. But if it's something you added locally that made your build succeed, this won't work as the APKs would differ. In which case we just have to wait for your next (maintenance/hotfix) release.

As long as your APK is fine (and not broken), this is no big deal: the update itself was _not_ held back, just the RB shield.

That said: Good you have those lint checks in place, so such things are getting caught! :star_struck:

**Comment by sosauce** [comment]
So here is what happened on my end :

I removed some strings in english, I tried building the apk, got the lint error,  added back the strings in english, tried building again and it worked ! As they are unused strings, I'll manually delete them from every language to be sure theres no errors

Hope this makes everything abit clearer 🤗

**Comment by IzzySoft** [comment]
And after you've added the strings back, you've committed those changes to the repo before building the app, or not? Because if not, what the verification builders get is the code with the strings missing, lint yelling and the build failing. Hence the "first basic rule" in our [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) say to always build from a clean tree at the commit the tag points to" :wink:

**Comment by IzzySoft** [comment]
Good to have a "human reminder", huh? :rofl: Next release should fix that then (don't change the already distributed one, please).

**Comment by IzzySoft** [comment]
Thanks, went through fine with yesterday's update batch :partying_face:
