### ISSUE TITLE
Remove unnecessary permission.

### ISSUE THREAD

**Issue by git10700** [sosauce/CuteMusic#6]
I think this is unused permission: android.permission.ACCESS_NETWORK_STATE

Thank you for the great music player.

**Comment by sosauce** [comment]
What I have this permission ?? Big oopsies

**Comment by sosauce** [comment]
Where is it ? Legit cant see it in the manifest 😅

**Comment by sosauce** [comment]
Huh, its weird cuz I never declared it..
