### ISSUE TITLE
Feature Request: read lyrics from the music file.

### ISSUE THREAD

**Issue by ghost** [sosauce/CuteMusic#7]

**Comment by gargamel17** [comment]
Yes, reading embedded lyrics is a must

**Comment by sosauce** [comment]
Will deffo add!

**Comment by tuuhin** [comment]
@gargamel17 
Is reading embedded lyrics is supported by android , is there any media api for that ?

**Comment by sosauce** [comment]
@tuuhin I've search but it doesn't seem like it, need to find a library for that

**Comment by tuuhin** [comment]
I don't think music files have embedded lyrics on it, some may have but not all 
So, you can't directly show lyrics 
You can check a third party Api like [lrclib](https://lrclib.net/docs)  to get the synced lyrics by querying track name and artist name.

**Comment by gargamel17** [comment]
Music files have embedded lyrics if user previously add them. Player should just display tags content

**Comment by sosauce** [comment]
Musics do have embedded lyrics, sadly not easily supported by Android. I also stand for not connecting my app to the internet

**Comment by tuuhin** [comment]
Yup I agree that music files have embedded lyrics but not all music files have
And it's hard to read then directly, and on the fact that you aren't connecting your app to the internet
This feature will be very tough to implement

**Comment by sosauce** [comment]
Some other apps have it, I'll find a library 💪

**Comment by realeatham** [comment]
Also support for .lrc lyrics as well would be nice

**Comment by sosauce** [comment]
> Also support for .lrc lyrics as well would be nice

This should be easier so I'll try fit it in in v1.4

**Comment by realeatham** [comment]
If you want I can supply some .lrc and .mp3 files for some songs for testing

**Comment by sosauce** [comment]
Thanks ! But I have the necessary already It's just that I have an internship so I don't have much time to work on it at the moment 😿

**Comment by sosauce** [comment]
Finally avaible !!!
