### ISSUE TITLE
Testing results: Galaxy S10e w/ LineageOS 20

### ISSUE THREAD

**Issue by lucmsilva651** [sosauce/CuteMusic#9]
The app works perfectly as in my tests.
I have not found any bug or crashes.

Some screenshots below:
![](https://telegra.ph/file/7eac196fb2868fa3c906f.jpg)
![](https://telegra.ph/file/926270e84fec4c9e989b3.jpg)
![](https://telegra.ph/file/5e3d10359a30ad29ade0b.jpg)

**Comment by sosauce** [comment]
Great to hear ! Hope it will continu with future updates ^^
